check_interval: 5s
timeout: 10s
sites:
  - name: "Google"
    url: "https://google.com"
  - name: "GitHub"
    url: "https://github.com"
  - name: "Not existing site"
    url: "https://unavailable-123-qwerty-site.com"
  - name: "Microsoft"
    url: "https://microsoft.com"
  - name: "Localhost"
    url: "http://localhost:3030"
  - name: "VK"
    url: "https://vk.com"
  - name: "AMD"
    url: "https://amd.com"
  - name: "Nvidia"
    url: "https://nvidia.com"
  - name: "Gmail"
    url: "https://gmail.com"
server:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 15s
  shutdown_timeout: 5s
pool:
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: 1h
  max_conn_idle_time: 30m