// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Возвращает текущий статус сервиса, аптайи, версию и статус зависимостей (пока пусто)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверка доступности (здоровья) сервиса",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.HealthResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Быстрая проверка доступности сервиса",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Пинг-понг",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PingResponse"
                        }
                    }
                }
            }
        },
        "/sites": {
            "get": {
                "description": "Получить список всех сайтов, находящихся на мониторинге",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Список сайтов",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Site"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Добавляет новый сайт для проверки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Добавить сайт",
                "parameters": [
                    {
                        "description": "Данные сайта",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateSiteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Site"
                        }
                    },
                    "400": {
                        "description": "invalid json body или ошибка валидации",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "url already exists",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sites/{id}": {
            "delete": {
                "description": "Удаляет сайт из мониторинга по его UUID",
                "tags": [
                    "sites"
                ],
                "summary": "Удалить сайт",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID сайта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid id format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "site not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sites/{id}/status": {
            "get": {
                "description": "Возвращает результаты последней проверки сайта",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sites"
                ],
                "summary": "Статус сайта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id сайта",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.SiteStatus"
                        }
                    },
                    "400": {
                        "description": "invalid id format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "site not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CreateSiteRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.HealthResponse": {
            "type": "object",
            "properties": {
                "dependencies": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "domain.PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "domain.Site": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "domain.SiteStatus": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "last_check_time": {
                    "type": "string"
                },
                "response_code": {
                    "type": "integer"
                },
                "response_time": {
                    "type": "integer"
                },
                "status": {
                    "description": "ok, pending, error",
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Go Service Monitor API",
	Description:      "API для мониторинга доступности сайтов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
